# Generated by Django 4.2.30 on 2026-07-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64)),
                ('range_from', models.PositiveIntegerField()),
                ('range_to', models.PositiveIntegerField()),
                ('mode', models.CharField(max_length=8)),
                ('total', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
