# Generated by Django 4.2.30 on 2026-07-06 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
                ('character', models.CharField(db_index=True, max_length=4, unique=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=20)),
                ('reading', models.CharField(db_index=True, max_length=40)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compounds', to='kanji.kanji')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
