# Generated by Django 4.2.30 on 2026-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='stroke_svg',
            field=models.TextField(blank=True, default=''),
        ),
    ]
